# Generated by Django 4.1.5 on 2023-03-05 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0002_diziler_category_filimler_category_populer_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='diziler',
            name='imdb',
            field=models.FloatField(default=0, verbose_name='IMDb Oranı'),
        ),
        migrations.AddField(
            model_name='filimler',
            name='imdb',
            field=models.FloatField(default=0, verbose_name='IMDb Oranı'),
        ),
        migrations.AddField(
            model_name='populer',
            name='imdb',
            field=models.FloatField(default=0, verbose_name='IMDb Oranı'),
        ),
    ]
