# Generated by Django 4.1.5 on 2023-03-05 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0004_diziler_tur_filimler_tur_populer_tur'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Diziler',
            new_name='Dizilerim',
        ),
    ]
