# Generated by Django 4.1.5 on 2023-03-07 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0005_rename_diziler_dizilerim'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='populer',
            name='category',
        ),
        migrations.DeleteModel(
            name='Filimler',
        ),
        migrations.DeleteModel(
            name='Populer',
        ),
    ]
