# Generated by Django 4.1.5 on 2023-03-07 10:46

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('appUser', '0002_userinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='phone_number',
            field=phone_field.models.PhoneField(blank=True, help_text='Telefon Numarası', max_length=31),
        ),
    ]
